/**
 * Single source of recurring Bahasa Melayu UI terms.
 * Views import from here; they never inline recurring terms (Req 5.1–5.3, 5.6, 5.7).
 */
export const T = Object.freeze({
  app: { name: 'Penjana Minit Mesyuarat', subtitle: 'Sektor Awam Malaysia', tabTitle: 'Penjana Minit Mesyuarat' },
  nav: { history: 'Sejarah', tracker: 'Penjejak', ingest: 'Ekstrak AI', newMeeting: 'Minit Baharu', label: 'Navigasi utama' },
  actions: {
    view: 'Lihat', edit: 'Sunting', delete: 'Padam', download: 'Muat Turun', preview: 'Pratonton',
    save: 'Simpan', cancel: 'Batal', close: 'Tutup', retry: 'Cuba Lagi', add: 'Tambah', remove: 'Buang',
    clear: 'Kosongkan', upload: 'Muat Naik', replace: 'Ganti', backToForm: 'Kembali ke Borang',
    generate: 'Jana Minit Mesyuarat', extract: 'Ekstrak dengan AI', clearSearch: 'Kosongkan Carian',
    more: 'Tindakan lain',
  },
  status: {
    draft: 'Draf', done: 'Selesai', notStarted: 'Belum Mula', inProgress: 'Sedang Berjalan',
    overdue: 'Tertunggak', unknown: 'Tidak Diketahui',
  },
  headings: { error: 'Ralat', success: 'Berjaya', info: 'Makluman' },
  messages: {
    genericError: 'Operasi gagal. Sila cuba lagi.',
    noDate: 'Tiada tarikh', noLocation: 'Tiada tempat', unassigned: 'Belum Ditetapkan',
    loading: 'Memuatkan...', saving: 'Menyimpan...', saveFailed: 'Gagal disimpan',
    savedAt: (hhmm) => `Disimpan pada ${hhmm}`, autosaveIdle: 'Auto-simpan aktif',
    extracting: 'Mengekstrak minit...',
    aiDraftNotice: 'Kandungan ini ialah draf yang dijana oleh AI. Sila semak dan sahkan sebelum dijadikan rekod rasmi.',
    modelDownloading: 'Model Whisper sedang dimuat turun buat kali pertama. Transkripsi seterusnya tidak perlu melalui langkah ini.',
  },
  ops: { // operation names used in success/error toasts
    save: 'Menyimpan minit', generate: 'Menjana minit mesyuarat', delete: 'Memadam minit',
    loadFile: 'Memuatkan fail', transcribe: 'Transkripsi audio', extract: 'Pengekstrakan AI',
    loadMeeting: 'Memuatkan rekod minit', loadMeetings: 'Memuatkan senarai mesyuarat',
    autosave: 'Auto-simpan draf', statusSave: 'Mengemas kini status tindakan', templateRead: 'Membaca fail templat',
    navigateFlush: 'Draf tidak dapat disimpan. Anda kekal di halaman penyuntingan.',
  },
  success: {
    save: 'Minit berjaya disimpan.', generate: 'Minit mesyuarat berjaya dijana dan disimpan.',
    delete: 'Minit mesyuarat berjaya dipadam.', loadFile: (name) => `Fail berjaya dimuatkan: ${name}`,
    transcribe: 'Transkripsi audio selesai.',
  },
  views: {
    history: { title: 'Sejarah Minit Mesyuarat', description: 'Semak, sunting dan muat turun minit mesyuarat yang telah disimpan.' },
    tracker: { title: 'Penjejak Tindakan Susulan', description: 'Pantau status dan tarikh akhir tindakan susulan daripada semua mesyuarat.' },
    ingest: { title: 'Ekstrak Minit dengan AI', description: 'Muat naik audio atau teks transkrip, kemudian ekstrak draf minit untuk disemak.' },
    editor: { title: 'Penyuntingan Minit Mesyuarat', description: 'Lengkapkan dan sahkan kandungan minit mengikut format PKPA Bil. 2/1991.' },
  },
  history: {
    summary: 'Ringkasan', total: 'Jumlah Mesyuarat', filterLegend: 'Tapis Mengikut Status', all: 'Semua',
    searchLabel: 'Cari mesyuarat', searchPlaceholder: 'Tajuk, pengerusi, tempat atau tarikh',
    emptyTitle: 'Belum ada minit mesyuarat',
    emptyDescription: 'Cipta minit baharu atau ekstrak draf minit daripada rakaman mesyuarat.',
    noMatchTitle: 'Tiada rekod sepadan dengan carian',
    noMatchDescription: 'Cuba laraskan kata carian atau penapis status.',
    downloadDocx: 'Muat Turun DOCX', untitled: 'Tanpa tajuk',
    moreFor: (title) => `Tindakan lain: ${title}`,
  },
  tracker: {
    total: 'Jumlah', statsLabel: 'Ringkasan status tindakan susulan',
    completionTitle: 'Kadar Penyelesaian', completionLabel: 'Kadar penyelesaian tindakan susulan',
    completionSummary: (done, total) => `${done} daripada ${total} tindakan selesai`,
    searchLabel: 'Cari tindakan', searchPlaceholder: 'Cari tugasan, pegawai, atau mesyuarat...',
    statusFilterLabel: 'Tapis status', allStatuses: 'Semua Status',
    listTitle: 'Senarai Tindakan Susulan',
    shownCount: (shown, total) => `${shown} daripada ${total} tindakan dipaparkan`,
    caption: 'Senarai tindakan susulan daripada semua mesyuarat',
    colTask: 'Tindakan', colAssignee: 'Tanggungjawab', colDeadline: 'Tarikh Akhir', colMeeting: 'Mesyuarat', colStatus: 'Status',
    updateStatusFor: (task) => `Kemas kini status: ${task}`,
    noTask: 'Tiada keterangan', untitledMeeting: 'Tanpa tajuk',
    emptyTitle: 'Tiada tindakan susulan',
    emptyDescription: 'Tindakan susulan daripada minit mesyuarat akan dipaparkan di sini.',
    noMatchTitle: 'Tiada tindakan sepadan dengan carian',
    noMatchDescription: 'Cuba laraskan kata carian atau penapis status.',
  },
  ingest: {
    templateTitle: 'Templat Format Minit',
    templateDescription: 'Pilih templat yang menentukan struktur minit yang diekstrak.',
    templateLabel: 'Templat',
    templateStandard: 'Templat Biasa (Standard Kerajaan)',
    templateCustom: 'Templat Khusus',
    templateStandardTag: 'Templat biasa akan digunakan',
    templateCustomTag: 'Templat khusus akan digunakan',
    templateLoadedSuffix: '(dimuatkan)',
    templateStructure: 'Struktur Templat',
    templateEmptyTitle: 'Tiada Templat Khusus Disimpan',
    templateEmptyDescription: 'Sila muat naik fail templat (.docx / .txt / .md) organisasi anda atau pilih Templat Biasa.',
    templateUpload: 'Muat Naik Templat',
    templateReplace: 'Ganti Templat',
    templateLoadedNote: 'Templat khusus berjaya dimuatkan. Pilih "Ganti Templat" untuk menukarnya.',
    templateMissingNote: 'Tiada templat khusus dimuatkan. Muat naik fail templat untuk menggunakannya.',
    uploadTitle: 'Muat Naik Dokumen / Audio Mesyuarat',
    uploadDescription: 'Pilih atau seret fail audio atau teks. Enjin Whisper mentranskripsikan audio secara tempatan.',
    modelLabel: 'Model Whisper',
    modelHelper: 'Model yang lebih besar lebih tepat tetapi lebih perlahan.',
    models: {
      tiny: 'Tiny (~75MB, sangat pantas)',
      base: 'Base (~145MB, pantas dan seimbang)',
      small: 'Small (~480MB, standard)',
      large: 'Large-v3-turbo (~1.6GB, sangat tepat)',
    },
    dropIdle: 'Klik atau seret fail ke sini',
    dropActive: 'Lepaskan fail di sini',
    dropBusy: 'Mentranskripsi fail audio...',
    acceptedFormats: 'Format diterima: MP3, WAV, M4A, TXT',
    modelDownloadingTitle: 'Memuat turun model Whisper',
    progressLabel: 'Kemajuan transkripsi',
    stages: {
      downloading: 'Memuat turun model Whisper',
      transcribing: 'Mentranskripsi audio',
      transcribed: 'Transkripsi selesai',
      transcribeFailed: 'Transkripsi gagal',
      extracting: 'Mengekstrak minit...',
      extracted: 'Pengekstrakan selesai',
      extractFailed: 'Pengekstrakan gagal',
    },
    readingText: (name) => `Membaca fail teks: ${name}...`,
    textLoaded: (name) => `Fail teks dimuatkan: ${name}`,
    readFailed: 'Ralat membaca fail.',
    processingAudio: (model, name) => `Memproses audio dengan Whisper (${model}): ${name}`,
    transcribeDone: (name) => `Transkripsi siap sepenuhnya untuk: ${name}`,
    transcribeFailedStatus: 'Ralat pemprosesan audio.',
    streamStartFailed: 'Ralat memulakan penstriman audio.',
    restored: 'Transkrip dipulihkan daripada sesi sebelumnya.',
    extractTitle: 'Pengekstrak AI: Transkrip ke Minit',
    extractDescription: 'Teks transkripsi dipaparkan di sini secara langsung, atau tampal teks perbincangan.',
    transcriptLabel: 'Teks transkrip',
    transcriptPlaceholder: 'Transkrip teks perbincangan mesyuarat akan dipaparkan di sini...',
    transcriptRequired: 'Sila masukkan teks transkrip.',
    downloadGroup: 'Muat turun transkrip',
    downloadTxt: 'Muat turun sebagai teks biasa (.txt)',
    downloadJson: 'Muat turun sebagai JSON (.json)',
    downloadSrt: 'Muat turun sebagai sari kata (.srt)',
    untitledMeeting: 'Mesyuarat Tanpa Tajuk',
    discussionPrefix: (title) => `Perbincangan: ${title}`,
  },
  editor: {
    actionBarLabel: 'Tindakan minit',
    aiDraftTitle: 'Draf AI',
    participant: (n) => `Ahli ${n}`,
    agendaItem: (n) => `Perkara ${n}`,
    actionItem: (n) => `Tindakan ${n}`,
    removeParticipant: (n) => `Buang ahli ${n}`,
    removeAgendaItem: (n) => `Buang perkara ${n}`,
    removeActionItem: (n) => `Buang tindakan ${n}`,
    addParticipant: 'Tambah Ahli',
    addAgendaItem: 'Tambah Perkara',
    addActionItem: 'Tambah Tindakan',
    noParticipants: 'Tiada ahli ditambah lagi.',
    noAgendaItems: 'Tiada perkara agenda ditambah lagi.',
    noActionItems: 'Tiada tindakan susulan ditambah lagi.',
    untitledMeeting: 'Mesyuarat Tanpa Tajuk',
    fields: {
      title: 'Tajuk Mesyuarat', titlePlaceholder: 'Contoh: Mesyuarat Jawatankuasa Teknikal Bil. 3/2026',
      number: 'Bilangan Mesyuarat', numberPlaceholder: 'Contoh: 3/2026',
      date: 'Tarikh',
      location: 'Tempat', locationPlaceholder: 'Contoh: Bilik Mesyuarat Utama, Tingkat 3',
      startTime: 'Masa Mula', endTime: 'Masa Tamat',
      chairName: 'Nama Pengerusi', chairNamePlaceholder: 'Nama penuh pengerusi',
      chairRole: 'Jawatan Pengerusi', chairRolePlaceholder: 'Contoh: Ketua Setiausaha',
      secretaryName: 'Nama Pencatat', secretaryNamePlaceholder: 'Nama penuh pencatat minit',
      secretaryRole: 'Jawatan Pencatat', secretaryRolePlaceholder: 'Contoh: Penolong Setiausaha',
      participantName: 'Nama', participantPosition: 'Jawatan',
      participantOrg: 'Organisasi / Bahagian', participantStatus: 'Status Kehadiran',
      mattersArising: 'Perkara berbangkit',
      mattersArisingHelper: 'Tindakan susulan dari mesyuarat lepas yang perlu dimaklumkan.',
      mattersArisingPlaceholder: 'Contoh: Laporan tindakan dari mesyuarat lepas (Bil. 2/2026) oleh Unit A',
      agendaTitle: 'Tajuk Perkara', agendaTitlePlaceholder: 'Tajuk agenda / perkara',
      agendaSummary: 'Ringkasan Perbincangan', agendaSummaryPlaceholder: 'Huraikan perbincangan yang berlaku...',
      agendaDecision: 'Keputusan / Ketetapan', agendaDecisionPlaceholder: 'Nyatakan keputusan atau ketetapan mesyuarat...',
      actionTask: 'Tindakan', actionTaskPlaceholder: 'Huraikan tindakan yang perlu diambil...',
      actionAssignee: 'Tanggungjawab (Nama / Jawatan)', actionAssigneePlaceholder: 'Nama atau jawatan pegawai',
      actionDeadline: 'Tarikh Akhir', actionStatus: 'Status',
    },
    attendance: { present: 'Hadir', absentExcused: 'Tidak Hadir - Bersebab', inAttendance: 'Turut Hadir' },
  },
  months: ['Januari', 'Februari', 'Mac', 'April', 'Mei', 'Jun', 'Julai', 'Ogos', 'September', 'Oktober', 'November', 'Disember'],
});
